# Generated by Django 4.0.7 on 2022-10-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empBirthDate',
            field=models.DateField(null=True),
        ),
    ]
