# Generated by Django 4.0.7 on 2022-10-17 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employee_empbirthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='empLastLogin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='empPassword',
        ),
    ]
